version: '3.8'

services:
  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    restart: unless-stopped
    command: npm run start