version: '3.8'

services:
  next-app:
    container_name: yrgn-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    restart: unless-stopped
    command: npm run start