version: "3.8"

services:
  app:
    container_name: yrgn-frontend
    build:
      context: ./next-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    command: npm run start
    networks:
      - my_network


networks:
  my_network:
    external: true