name: YRGN CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH Key
      run: |
        mkdir -p $HOME/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/key
        chmod 600 $HOME/.ssh/key

    - name: Deploy
      run: |
        "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no"
        ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "cd ${{secrets.PROJECT_FOLDER}} && git pull"
        ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "cd ${{secrets.PROJECT_FOLDER}} && docker-compose up --build -d"
