name: YRGN CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Build and deploy
      run: |
        ssh-copy-id ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}
